# This workflow will setup Python, run create_perf_json.py, and archive
# perf JSON files.

name: Create perf json

on:
  push:
  pull_request:
  schedule:
    # Tuesdays at 9AM PST
    - cron: '0 16 * * 2'

permissions:
  contents: read

jobs:
  create-perf-json:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout perfmon
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Python 3.x
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.x"

    - name: Run unittests
      working-directory: ./scripts/unittesting
      run: python -m unittest metric_test.py test_create_perf_json.py

    - name: Create perf json files
      working-directory: ./scripts
      run: python create_perf_json.py -v

    - name: Archive perf json files
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: perf-json
        path: scripts/perf
        retention-days: 10
        if-no-files-found: error
